### ISSUE TITLE
Don't use releases?

### ISSUE THREAD

**Issue by sfrdmn** [cssconf/2017-assets#3]
It's probably not worth it to use releases here, since every new release requires all consuming repos to update their package.json files. We should maybe just point to `master` in the consuming repos and only add tags/releases _if_ we need them

**Comment by lukaszklis** [comment]
We could use this approach during a development of a specific project, such as the main website. After the first version is released to the public, we could go back to versioning (same would apply to the sponsorship page) – WDYT?

**Comment by sfrdmn** [comment]
sounds good 👍

**Comment by usefulthink** [comment]
yes please, just have it point to master.

**Comment by lukaszklis** [comment]
Already updated the main site: cssconf/2017.cssconf.eu@4b59197ddec7cbe4c841925b62c2f75709bbedd7.

**Comment by lukaszklis** [comment]
Sponsorship page is also using the latest version now.
